-- AlterTable: add consecutiveSyncFailures to SchoolConnection and CanvasConnection.
--
-- This migration was hand-written rather than generated by `prisma migrate
-- dev` (that command's shadow database is broken in this project's Neon
-- setup). The schema.prisma changes it captures were originally applied to
-- a dev database via startup.ts PATCHES. This file exists so that production,
-- whose boot sequence runs `prisma migrate deploy`, receives the columns.

-- SchoolConnection: tracks consecutive HAC/PowerSchool sync failures
ALTER TABLE "SchoolConnection" ADD COLUMN IF NOT EXISTS "consecutiveSyncFailures" INTEGER NOT NULL DEFAULT 0;

-- CanvasConnection: tracks consecutive Canvas sync failures
ALTER TABLE "CanvasConnection" ADD COLUMN IF NOT EXISTS "consecutiveSyncFailures" INTEGER NOT NULL DEFAULT 0;
