-- AlterTable: add COPPA DOB verification fields to User.
--
-- This migration was hand-written rather than generated by `prisma migrate
-- dev` (that command's shadow database is broken in this project's Neon
-- setup). The schema.prisma changes it captures were originally applied to
-- a dev database via `prisma db push`, which does NOT create a migration
-- file — so production, whose boot sequence runs `prisma migrate deploy`,
-- never received these columns. This file exists to close that gap.

-- CreateEnum
DO $$ BEGIN
  CREATE TYPE "AccountStatus" AS ENUM ('ACTIVE', 'DOB_MISMATCH_LOCKED', 'UNDER_13_BANNED');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "accountStatus" "AccountStatus" NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "hacDateOfBirth" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bannedUntilDate" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "dobCorrectionAttempts" INTEGER NOT NULL DEFAULT 0;
